CREATE TABLE EMP7
(ID INT PRIMARY KEY,NAME VARCHAR(50),SALARY INT)

INSERT INTO EMP7 VALUES (1,'AISHU',90000),
(2,'RUPALI',80000),
(3,'KISHOR',75000),
(4,'SUSHANT',80000),
(5,'AKSHU',70000),

INSERT INTO EMP7 VALUES(6,'ABCD',78000)

SELECT * FROM EMP7


CREATE TRIGGER TR
ON EMP6
AFTER INSERT
AS BEGIN
		PRINT 'HELLO DEVELOPER NEW RECORD INSERTED SUCCESSFULLY'
END	    

INSERT INTO EMP7 VALUES (7,'ASZ',65000)

CREATE TRIGGER TR22
ON EMP7
AFTER INSERT
AS BEGIN
		PRINT 'HELLO DEVELOPER NEW RECORD INSERTED SUCCESSFULLY'
END

INSERT INTO EMP7 VALUES (9,'ABC',65000)


CREATE TRIGGER TR3
ON EMP7
AFTER UPDATE 
AS BEGIN
	PRINT 'HELLO DEVELOPER EXISTING RECORD UPDATE SUCCESSFULLY!'
END

UPDATE EMP7 SET NAME='AISHWARYA' WHERE ID=1


CREATE TRIGGER TR23
ON EMP7
AFTER DELETE
AS BEGIN 
		PRINT 'HELLO DVELOPER RECORD DELETED SUCCESSFULLY!'
END

DELETE FROM EMP7 WHERE ID=6


CREATE TRIGGER TR54
ON EMP7
AFTER INSERT
AS BEGIN
		SELECT * FROM INSERTED
		PRINT 'CURRENT RECORD INSERTED SUCCESSFULLY!'
END

INSERT INTO EMP7 VALUES (11,'ABC',65000)

CREATE TRIGGER TR66
ON EMP7
AFTER UPDATE
AS BEGIN
		SELECT * FROM INSERTED
		END

CREATE TRIGGER TR7
ON EMP7
AFTER UPDATE 
AS BEGIN
		SELECT* FROM DELETED
END

DELETE FROM EMP7 WHERE ID=11 




