#ON DATABASE is used for DDL triggers (CREATE, ALTER, DROP), not for inserting rows.


CREATE TABLE STUD
(ID INT,NAME VARCHAR(50))

CREATE TRIGGER TR11
ON DATABASE
AFTER CREATE_TABLE
AS 
BEGIN
	PRINT 'HELLO DEVELOPER - NEW TABLE CREATED SUCCCESSFULLY!'
END

CREATE TABLE STUD
(ID INT,NAME VARCHAR(50))


CREATE TRIGGER TR33
ON DATABASE
AFTER ALTER_TABLE
AS
BEGIN
    PRINT 'HELLO DEVELOPER - TABLE ALTERED SUCCESSFULLY!';
END;


ALTER TABLE STUD ADD COUNTRY VARCHAR(50)
ALTER TABLE STUD ADD address VARCHAR(50)
ALTER TABLE STUD ADD age int


create trigger tr44
on database
after drop_table
as
begin
		print 'hello developer table dropped successfully!'
end

drop table stud

