SELECT * FROM EMP6

SELECT UPPER(NAME) FROM EMP6 
SELECT LOWER (CITY) FROM EMP6
SELECT LTRIM(      NAME      ) FROM EMP6
SELECT RTRIM('A'     ) FROM EMP6 WHERE EMPID=1
SELECT CONCAT('AISHU',   'ZINJURTE') FROM EMP6
