USE student

CREATE TABLE STUD02
(ID INT, NAME VARCHAR(50))

SELECT * FROM STUD02
create trigger tr21
on stud02
instead of insert
as
begin
	print 'HELLO DEVELOPER DO NOT INSERT ANY RECORD IN THIS TABLE ITS RESTRICTED!'
END

INSERT INTO STUD02 VALUES (15,'SUNITA')

CREATE TRIGGER TR31
ON STUD02
INSTEAD OF UPDATE
AS BEGIN
		PRINT 'HELLO DEVELOPER DO NOT UPADATE ANY RECORD IN THIS TABLE ITS RESTRICTED!'
END

UPDATE STUD02 SET NAME='AZ' WHERE ID=1

CREATE TRIGGER TR41
ON STUD02
INSTEAD OF DELETE
AS BEGIN
		PRINT 'HELLO DEVELOPER DO NOT DELETE ANY RECORD IN THIS TABLE ITS RESTRICTED'
END

DELETE FROM STUD02 WHERE ID =15









