create database clauses
use clauses

create table Demo1
(
 ID INT PRIMARY KEY,NAME VARCHAR (20), PRODUCT VARCHAR (50) , PRICE INT
 )

 SELECT * FROM DEMO1

 INSERT INTO DEMO1 VALUES 
 ( 1,'AISHU','IPHONE',1000000),
 ( 2,'KISHU','VIVO',23000),
 ( 3,'AISHU','IPHONE',67000),
 ( 4,'AISHU','VIVO',19000),
 ( 5,'PIYU','IPHONE',350000),
 ( 6,'AISHU','MI',50000),
 ( 7,'KISHU','MI',40000),
 ( 8,'AISHU','VIVO',150000),
 ( 9,'RIYU','IPHONE',1020000),
 ( 10,'PIYU','SAMSUNG',9000)

 SELECT COUNT (PRICE) , NAME FROM DEMO1
 GROUP BY NAME

 SELECT MAX(PRICE),PRODUCT FROM DEMO1
 GROUP BY PRODUCT

 SELECT MIN (PRICE),PRODUCT 
 FROM DEMO1
 GROUP BY PRODUCT

 SELECT AVG (PRICE),PRODUCT 
 FROM DEMO1
 GROUP BY PRODUCT

 SELECT SUM (PRICE),PRODUCT
 FROM DEMO1
 GROUP BY PRODUCT


SELECT COUNT(PRODUCT),NAME 
FROM DEMO1
GROUP BY NAME

SELECT SUM(PRICE),PRODUCT FROM DEMO1
GROUP BY PRODUCT 
HAVING COUNT(PRODUCT) > 3 

SELECT COUNT(PRODUCT),NAME
FROM DEMO1
GROUP BY NAME
HAVING MAX(PRICE)> 10000