CREATE TABLE Department
(
    DeptID INT PRIMARY KEY,
    DeptName VARCHAR(50)
)

CREATE TABLE Employee
(
    EmpID INT PRIMARY KEY,
    EmpName VARCHAR(50),
    DeptID INT,
    ManagerID INT,
    Salary DECIMAL(10,2),
    FOREIGN KEY (DeptID) REFERENCES Department(DeptID)
)

CREATE TABLE Project
(
    ProjectID INT PRIMARY KEY,
    ProjectName VARCHAR(50)
)

CREATE TABLE EmployeeProject
(
    EmpID INT,
    ProjectID INT,
    PRIMARY KEY(EmpID, ProjectID),
    FOREIGN KEY(EmpID) REFERENCES Employee(EmpID),
    FOREIGN KEY(ProjectID) REFERENCES Project(ProjectID)
)
 SELECT * FROM DEPARTMENT
 SELECT * FROM EMPLOYEE
 SELECT * FROM PROJECT
 SELECT * FROM EmployeeProject


INSERT INTO Department VALUES (1,'HR'),
(2,'IT'),
(3,'FINANCE'),
(4,'SALE')

INSERT INTO EMPLOYEE VALUES (101,'A',1,101,9000),
(102,'B',1,NULL,9000),
(103,'C',2,101,10000),
(104,'D',3,102,8000),
(105,'E',NULL,101,22000),
(106,'F',2,104,66000),
(107,'G',1,106,12000)

INSERT INTO Project VALUES
(1,'ERP'),
(2,'CRM'),
(3,'Payroll'),
(4,'Website');

INSERT INTO EmployeeProject VALUES
(101,1),
(101,2),
(102,1),
(103,2),
(104,3),
(106,1),
(106,4),
(107,3);

SELECT EMPLOYEE.EMPNAME,Department.DEPTNAME FROM EMPLOYEE INNER JOIN Department ON Employee.EMPID=Department.DEPTID

SELECT PROJECT.ProjectName,EMPLOYEE.EMPNAME FROM PROJECT INNER JOIN EMPLOYEE ON PROJECT.PROJECTID = EMPLOYEE.EMPID
SELECT EMPLOYEE.EMPNAME,Department.DEPTNAME FROM EMPLOYEE LEFT JOIN Department ON Employee.EMPID=Department.DEPTID
SELECT EMPLOYEE.EMPNAME,Department.DEPTNAME FROM EMPLOYEE RIGHT JOIN Department ON Employee.EMPID=Department.DEPTID
SELECT PROJECT.ProjectName,EMPLOYEE.EMPID FROM PROJECT INNER JOIN EMPLOYEE ON PROJECT.PROJECTID = EMPLOYEE.EMPID WHERE Employee.EMPID IS NULL
