select * from emp6

select MAX(SALARY) FROM EMP6
SELECT MIN (SALARY) FROM EMP6
SELECT SUM (SALARY) FROM EMP6
SELECT COUNT (SALARY) FROM EMP6
SELECT AVG(SALARY) FROM EMP6
SELECT AVG(CONVERT(DECIMAL(10,2), Salary)) FROM Emp6;

