CREATE TABLE A( CUSTID INT, NAME VARCHAR (50),CITY VARCHAR (50))
INSERT INTO A VALUES
(1, 'Aishwarya', 'Pune'),
(2, 'Kishor', 'Mumbai'),
(3, 'Sushant', 'Pune'),
(4, 'Swarupa', 'Delhi'),
(5, 'Riya', 'Nashik')

select * from A

CREATE TABLE B (OID INT,NAME VARCHAR(50),CITY VARCHAR(50))

INSERT INTO B VALUES
(3, 'SUSH', 'Pune'),
(4, 'AISHU', 'Delhi'),
(5, 'Priya', 'Nashik'),
(6, 'RIYA', 'Mumbai'),
(7, 'PRATHMESH', 'Pune')

SELECT * FROM B

SELECT DISTINCT CUSTID FROM A
SELECT DISTINCT OID FROM B

SELECT CUSTID FROM A 
UNION 
SELECT OID FROM B

SELECT CUSTID FROM A
UNION ALL
SELECT OID FROM B

SELECT CUSTID FROM A
INTERSECT
SELECT OID FROM B

SELECT CUSTID FROM A
EXCEPT
SELECT OID FROM B

CREATE TABLE C
(ID INT)

INSERT INTO C VALUES(NULL),(NULL),(1),(2),(2),(3),(3),(4),(5),(6),(7)

CREATE TABLE D(ID INT)

INSERT INTO D VALUES(NULL),(NULL),(1),(1),(2),(2),(3),(4),(5),(6),(7),(8),(9)

SELECT DISTINCT ID FROM C
SELECT DISTINCT ID FROM D

SELECT ID FROM C
UNION
SELECT ID FROM D

