CREATE DATABASE DEMO1
CREATE TABLE EMP(EMPID INT PRIMARY KEY,EMPNAME CHAR(50),SALARY INT)
INSERT INTO EMP VALUES(11,'AKISHU',85000)
SELECT*FROM EMP

ALTER TABLE  EMP ADD  EMAIL VARCHAR(50)
ALTER TABLE EMP ALTER COLUMN EMAIL CHAR(50)
ALTER TABLE EMP DROP COLUMN EMAIL,name

UPDATE EMP SET EMAIL='AKISHUGMAIL.COM' WHERE EMPID=2
UPDATE EMP SET EMAIL='AK2003.COM'  

SELECT EMPNAME,SALARY FROM EMP

DELETE FROM EMP WHERE EMPID=1
DELETE FROM EMP

TRUNCATE TABLE EMP
DROP TABLE EMP



USE DEMO1
create table customer (AccountNo Bigint identity(65745676563748,4),name varchar(50))
select * from customer
insert into customer values('aishu')

