SELECT MAX(SALARY) FROM EMP8 WHERE SALARY < (SELECT MAX(SALARY) FROM EMP8)

SELECT MAX(SALARY) FROM EMP8
WHERE SALARY < (
    SELECT MAX(SALARY) FROM EMP8
    WHERE SALARY < (
        SELECT MAX(SALARY) FROM EMP8
    )
)

SELECT MAX(SALARY)
FROM EMP8
WHERE SALARY < (
    SELECT MAX(SALARY)
    FROM EMP8
    WHERE SALARY < (
        SELECT MAX(SALARY)
        FROM EMP8
        WHERE SALARY < (
            SELECT MAX(SALARY)
            FROM EMP8
        )
    )
)


SELECT MAX(SALARY) FROM EMP8 WHERE SALARY NOT IN (SELECT MAX(SALARY) FROM EMP8)